# Gebruik komma's om de verschillende JSON bronnen te scheiden
wishlist.urls=https://cobrab311.github.io/wishlist/kids/dev/paw-patrol/jonas_items.json,https://cobrab311.github.io/wishlist/kids/dev/paw-patrol/milan_items.json

# Gebruik het volledige pad naar je lokale bestanden
wishlist.localPaths=Z:/Programming/IdeaProjects/wishlist/kids/dev/paw-patrol/jonas_items.json,Z:/Programming/IdeaProjects/wishlist/kids/dev/paw-patrol/milan_items.json

# Crawler settings
crawler.bol.enabled=true
crawler.lego.enabled=false
crawler.amazon.enabled=true
crawler.dreamland.enabled=true
crawler.fnac.enabled=false
crawler.suprabazar.enabled=true
crawler.mediamarkt.enabled=true